name: SAM build deploy.
on:
  push:
    branches:
      - main
jobs:
  build-deploy-sam:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: setup python packages
        uses: actions/setup-python@v2
      
      - name: Sam setup
        uses: aws-actions/setup-sam@v1
      
      - name: aws cli configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      # sam build 
      - name: Sam build
        run: sam build --use-container
      # sam deploy
      - name: Sam deploy
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name elb-differernce --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-xg08sfanlri1 --capabilities CAPABILITY_IAM --region us-east-1
